name: hands_user_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 11.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^6.1.2
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.2.0
  intl: 
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  persistent_bottom_nav_bar_v2: ^5.2.3
  cupertino_icons: 
  vertical_card_pager: ^1.6.0
  appinio_swiper: ^2.1.1
  # FIREBASE
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.14
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  firebase_remote_config: ^4.3.13
  cloud_firestore: ^4.15.4
  firebase_database: ^10.5.4

  font_awesome_flutter: ^10.7.0
  # FIREBASE MESSAGING
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2

  # PUSH NOTIFICATION
  # onesignal_flutter: ^5.1.0

  # STATE MANAGEMENT
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.9
  iconsax: 

  # IMAGE
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  lottie: ^3.0.0

  # OTHER
  country_picker: ^2.0.24
  flutter_custom_tabs: ^1.2.1
  permission_handler: ^11.3.0
  flutter_html: ^3.0.0-beta.2
  firebase_pagination: ^3.1.0
  webview_flutter: ^4.7.0
  animated_bottom_navigation_bar: ^1.3.3
  pinput: ^4.0.0
  
  # SOCIAL LOGIN
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  
  #provider
  toggle_rotate: ^1.0.1
  android_intent_plus: ^4.0.3
  flutter_image_stack: ^0.0.7
  animate_do: ^3.3.4
  rate_in_stars: ^0.0.3
  conditional_builder_rec: ^1.0.0
  multi_select_flutter: ^4.1.3
  infinite_scroll_pagination: ^4.0.0
  file_picker: ^6.1.1
  #notifications:
  onesignal_flutter: ^5.1.0
  flutter_typeahead: ^5.2.0
  #chart
  syncfusion_flutter_charts: ^24.2.5
  # PAYMENT GATEWAYS
  midpay: ^1.1.7
  phonepe_payment_sdk: ^2.0.1
  crypto: 3.0.3
  qr_flutter: ^4.1.0 #required for in pix_flutter
  pix_flutter: ^2.2.0
  flutterwave_standard: ^1.0.8
  flutter_stripe: ^10.1.1
  cinetpay: ^1.0.7
  flutter_paypal_checkout:
    git:
      url: https://github.com/Raj-GMITS/flutter_paypal_checkout.git
      ref: main
      
  flutter_paystack:
    git:
      url: https://github.com/Raj-GMITS/flutter_paystack.git
      ref: master    

  # MAP
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  super_circle: ^1.0.0
  flutter_vibrate: ^1.3.0
  audioplayers: ^6.0.0
  timer_count_down: ^2.2.2
  loading_animation_widget: ^1.2.1

  flutter_localizations:
    sdk: flutter
  video_player: ^2.8.6
  animated_text_kit: ^4.2.2
  flutter_dropdown_search: ^0.0.4
  either_dart: ^1.0.0 
  animated_custom_dropdown: ^3.1.0
  path_provider: ^2.1.3
  flutter_progress_hud: ^2.0.2
  open_file: ^3.3.2
  flutter_pdfview: ^1.3.2
  flutter_keyboard_visibility: ^6.0.0
  flutter_polyline_points: ^2.1.0
  day_night_time_picker: ^1.3.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0+1
  flutter_launcher_icons: ^0.11.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter_icons:
  image_path: "assets/logo_large.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/
    - assets/flag/
    - assets/images/
    - assets/icons/upi_payment/
    - assets/lottie/
    - shorebird.yaml
